### ISSUE TITLE
10.3.1 Support

### ISSUE THREAD

**Issue by p0wer0n** [coffeebreakerz/CheekiJailbreeki#2]
Why is there no 10.3.1 support when the exploit supports it?

**Comment by coffeebreakerz** [comment]
I did not mention that 10.3.1 will be excluded, I just don't want to make the assumption that this exploit will work on 10.3.1 as well. The 10.2.1 exploit will use the same patches as the ones in Yalu102 because there has not been changed a thing as it comes to patches. If you understand the code you will come to know that everything in theory is written to be compatible with 10.3.1, even if it comes to KPP this code has been written to avoid it as much as possible by patching some things in userland. In other words: 10.3.1 support can be added in the future in theory and I will be the one to support it.
The offsets for 10.3.1 devices needed for the kernel exploit are already in this repository. They were found by Github user Mila432 and I gratefully thank him for those.

Stay tuned and perhaps try to compile the project yourself, it is not a jailbreak yet since we need to run Adam's exploit outside of the sandbox. The tripple_fetch exploit gives a launchd task with memory write and read access. This will eventually be used to execute Adam's exploit outside of the sandbox. At that time only the kernel patches will have to be added so if anybody can help creating code to run Adam's exploit outside of the sandbox using tripple_fetch it would speed up the process for both 10.3.1 and 10.2.1
