### ISSUE TITLE
jailbreakme103.js

### ISSUE THREAD

**Issue by Koizum1** [coffeebreakerz/CheekiJailbreeki#22]
What is this?
```
function exploit() {
    let arr = new Uint32Array(10);
    for (let i = 0; i < 0x100000; i++) {
        parseInt();
    }
    arr[8] = 1;
    arr[-0x12345678] = 2;
}

exploit();
```
You dropped in a PoC by a talented security researcher and called it an exploit.

**Comment by jakeajames** [comment]
There's code and it lets you control a register (don't remember which). So theoretically it's an exploit

Also @coffeebreakerz block Blu3Dev's alt pls

**Comment by Koizum1** [comment]
1. It is a PoC, not an exploit.

2. I don't know who that is, and if you think I am BlueDev, you are sick.

**Comment by Koizum1** [comment]
I don't know what is wrong with you. You should get some help. I came to ask what this useless code was doing in this project, and you play the alt card.

I don't know who you are talking about (although, I did find his/her Twitter (You 2 seem to go way back)).

**Comment by jakeajames** [comment]
1. An exploit is a piece of code which makes use of a vulnerability.
This will crash WebKit and write to a register. So yes, it is an exploit. Useful? No

2. Mate you can try one million times but you never will be able to convince me. I know you are Blu3Dev and you know that as well. You act like him, you talk like him, you have the same knowledge as him, you hate the exact same people (Coffeebreakers in this case), you both are passionated about downgrading, you appeared in the scene right after his alt account was banned in /r/jailbreak. The chance this is a coincidence is 0.00000001%. Actually 0%. It doesn't exist. You are him

**Comment by Koizum1** [comment]
1. Exactly, thats what I was asking, why is it here?

2. What is your problem with Eric? Seriously. I have been talking with him the past few days and he seems to be a nice dude. 

3. When did I ever hate on coffeebreakers? I am just confused by what they do (dropping in JS doesn't do much).

4. Ok? I joined reddit because my brother showed me a cat video and I asked him app it was. I was already aquatinted with the jailbreak community and found the /r/jailbreak and got hooked.

5. Alt account? As far as Eric has told me, he was just bluedev.

**Comment by Koizum1** [comment]
If you want to take this somewhere else, id be glad to.

**Comment by jakeajames** [comment]
> What is your problem with Eric? Seriously. I have been talking with him the past few days and he seems to be a nice dude.

You just confirmed it yourself now, Eric 😂

**Comment by Koizum1** [comment]
I know his name because he told me it.

I'm am not Eric.

**Comment by Koizum1** [comment]
My name is Toi. 

Again, if you have a problem with E, speak to him, not me. 

If you have a problem with me, let me know.

**Comment by coffeebreakerz** [comment]
Github is not a discussion board. It is good to discuss about subjects like this but please do it elsewhere.

As an addition I would like to state that the PoC by lokihardt is already an exploit. An exploit makes use of a vulnerability and Lokihardt's code does that as it writes an integer to register X2.
After doing research another PoC by lolihardt could be used rather than the one I was pointing out.
This does not take away the fact that I only stated that this PoC by lokihardt could in theory be used to create a jailbreakme webpage for 10.2.1 devices.
I think that's all to discuss.

**Comment by Koizum1** [comment]
My problem was that it was used nowhere and wasn't changed whatsoever.

**Comment by stek29** [comment]
@coffeebreakerz just lock the conversation

**Comment by coffeebreakerz** [comment]
My problem with people like you @Koizum1, is that they do not think before they move. Now I do not care about you losing a game. I don't play games. I only observe and analyse. If you actually read the commits, the comments in the javascript and the readme of this repository then everything would have been very clear to you. But that's not why you are here. You are here because you like to spit out an opinion on me in person. It's because you once chose that path to walk. And now you are check, you scribble back to your side of the field. I'm not playing games. I'm just a spectator, but take this from me if you do play make sure you do not lose. That's the only rule in any game.

**Comment by Koizum1** [comment]
Damn that was inspirational... 

All you really stated in the readme was:

> for his WebKit exploit that will lead to JailbreakMe 2017.

It wasn't really used anywhere. 

Also, is this project dead? Seems Saigon has overruled it.
