### ISSUE TITLE
Credit Luca correctly?

### ISSUE THREAD

**Issue by Blu3DevGit** [coffeebreakerz/CheekiJailbreeki#4]
I look into your shitty code and see Luca's yalu102 KPP bypass, maybe credit him for it?

Good luck. FAKE

**Comment by coffeebreakerz** [comment]
I did not use any of the code that Luca Todesco used. You clearly cannot read code. All I did was use his xcode build settings to get started fast with the right linker flags.
No actual code of him was used.
Since you are clearly spamming my Github repositories with issues that do not actually contribute to development and apart from that are not even correct critisism I will have to block you without any consent.
My appologies for that, but I need to keep my repositories professional and accessible to users.
